Fix #3
peluche1275/Kata_Bowling pull request #24
Opened 2021-02-10 10:32 UTC by peluche1275

More HTML usage

@cegerard

2021-02-10 19:57 UTC, cegerard commented on index.html
> +    </div>
👏

2021-02-10 20:04 UTC, cegerard requested changes

2021-02-10 20:04 UTC, cegerard commented on js/app.js
> +    const buttonStart = document.getElementById("startGame");
Au vu du code de la fonction je pense que le nom run n'est pas adapté.
La fonction ne "run" pas elle ajoute un écouteur d'évènement à ton bouton.

2021-02-10 20:04 UTC, cegerard commented on js/app.js
> +const form = document.getElementById("mainForm");
Je dis cela car il faut éviter autant que possible les variables global.
D'autant qu'ici ta constante form est initialisée une fois au chargement du fichier et c'es tout.

Cela veut dire que si ton formulaire doit évoluer avec ton application, ton js ne le verra pas.

2021-02-11 07:36 UTC, peluche1275 commented on js/app.js
> +    const buttonStart = document.getElementById("startGame");
D'accord, je note!

Je l'avais appelé comme ça car c'était la fonction qu'il fallait lancer pour que le bouton apparaisse et qu'on puisse utiliser l'app

2021-02-11 07:46 UTC, peluche1275 commented on js/app.js
> +const form = document.getElementById("mainForm");
D'accord je ferai en sorte d'éviter les constantes globales au possible. 

Mais pour moi ça ne me poser pas de problème, si je devais changer mon form je le vide avec **innerHTML = ''** et je lui ajoute des élèments et puis ça m'évitais de devoir retaper plusieurs fois **form = document.getElementById("mainForm")**.
C'est comme ça que j'ai vu les choses quand j'ai écris cette constante globales.

2021-02-11 12:34 UTC, cegerard commented on js/app.js
> +const form = document.getElementById("mainForm");
Ok, mais dans les fais dit toi qu'une variable globale c'est dangereux elle peut être modifiée n'importe où et par n'importe qui. C'est un ajout de complexité caché qui te posera forcément des problèmes.

Je pense que tu te compliques la vie avec le html côté js et tu risques d'avoir pas mal de perte de temps et de problèmes par la suite à générer ton code plutôt que de l'écrire dans un fichier (en sachant que tu peux avoir plusieurs page html).

Là j'ai l'impression que tu essais de faire  une SPA sans framework.

2021-02-11 12:34 UTC, cegerard commented on js/app.js
> +    const buttonStart = document.getElementById("startGame");
Ok, garde à l'esprit qu'une fonction doit être nommer en fonction des résultats qu'elle crée.

2021-02-11 12:34 UTC, cegerard commented on js/app.js
> +const form = document.getElementById("mainForm");
Enfin ce n'est pas grave de récupérer le formulaire dans chaque fonction.
Ca les rends indépendantes d'un état global. Et si tes fonctions sont chainées (appelé les unes dans les autres) tu peux aussi passer ton formulaire en paramètre des fonctions.

2021-02-12 11:30 UTC, closed without merging

2021-02-12 13:26 UTC, peluche1275 commented on js/app.js
> +const form = document.getElementById("mainForm");
Oui enfaites j'était dans l'optique de faire une SPA